apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-deployment
  namespace: interview-example-project
spec:
  replicas: 1
  selector:
    matchLabels:
      component: backend-api
  template:
    metadata:
      labels:
        component: backend-api
    spec:
      containers:
        - name: backend-api
          image: docker.io/21321321421441/interview-example-project-backend:latest
          ports:
            - containerPort: 4667
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: password
            - name: POSTGRES_HOST
              value: postgres-cluster-ip-service
