apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: interview.test
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-ip-service
                port:
                  number: 4667
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-ip-service
                port:
                  number: 80
