name: Run standard build pipeline after push for interview-example-project

on:
  push:
    branches:
      - master

jobs:
  build-backend-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          architecture: x64
          cache: 'maven'
      - name: Docker version
        run: docker compose version
      - name: Build the application
        working-directory: backend
        run: |
          echo "--------------"
          echo "Using maven version:"
          sh -c "mvn -v | grep 'Apache Maven'"
          echo "--------------"
          mvn package -DskipTests=true
      - name: Test the application
        working-directory: backend
        run: |
          echo "--------------"
          echo "Using maven version:"
          sh -c "mvn -v | grep 'Apache Maven'"
          echo "--------------"
          mvn integration-test