name: Create new deployment for interview-example-project

on:
  push:
    tags:
      - '*'

jobs:
  build-backend-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Build version information
        run: echo "Trying to build new pushed version ${{ github.ref }}"
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
          architecture: x64
          cache: 'maven'
      - name: Prepare pom file for release...
        working-directory: deployment_tools
        run: |
          git update-index --chmod=700 prepare_backend_image.sh
          ./prepare_backend_image.sh
      - name: Build the application
        working-directory: backend
        run: |
          echo "--------------"
          echo "Using maven version:"
          sh -c "mvn -v | grep 'Apache Maven'"
          echo "--------------"
          mvn package -DskipTests=true
      - name: Run maven tests
        working-directory: backend
        run: mvn test -DskipIntegrationTests=true
