name: Test interview-example-project

on:
  push:
    branches:
      - master

strategy:
  matrix:
    job: [ setup-backend-environment, build-backend-environment, run-backend-tests ]

jobs:
  setup-backend-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
          architecture: x64
          cache: 'maven'
  build-backend-environment:
    needs: [setup-backend-environment]
    steps:
      - name: Build the application
        working-directory: backend
        run: |
          echo "-----------------------------------"
          echo "Using maven version:"
          sh -c "mvn -v | grep 'Apache Maven'"
          echo "-----------------------------------"
          mvn package -DskipTests=true
  run-backend-tests:
    needs: [build-backend-environment]
    steps:
      - name: Run maven tests
        working-directory: backend
        run: mvn test -DskipIntegrationTests=true
